In [1]:
import spacy # importa a biblioteca spacy
import pandas as pd # importa a biblioteca pandas para lidar com tabelas

In [4]:
df = pd.read_csv("stocks.tsv", delimiter="\t") # carrega o arquivo tsv
df # exibe o conteúdo da tabela carregada

,Symbol,CompanyName,Industry,MarketCap
0,A,Agilent Technologies,Life Sciences Tools & Services,53.65B
1,AA,Alcoa,Metals & Mining,9.25B
2,AAC,Ares Acquisition,Shell Companies,1.22B
3,AACG,ATA Creativity Global,Diversified Consumer Services,90.35M
4,AADI,Aadi Bioscience,Pharmaceuticals,104.85M
...,...,...,...,...
5874,ZWRK,Z-Work Acquisition,Shell Companies,278.88M
5875,ZY,Zymergen,Chemicals,1.31B
5876,ZYME,Zymeworks,Biotechnology,1.50B
5877,ZYNE,Zynerba Pharmaceuticals,Pharmaceuticals,184.39M
5878,ZYXI,Zynex,Health Care Equipment & Supplies,438.33M

In [5]:
symbols = df.Symbol.tolist() # converte a coluna symbol do dataframe em uma lista
companies = df.CompanyName.tolist() # converte a coluna companyname em uma lista
print(symbols[:10]) # exibe os primeiros dez símbolos

['A', 'AA', 'AAC', 'AACG', 'AADI', 'AAIC', 'AAL', 'AAMC', 'AAME', 'AAN']

In [10]:
stops = ["two"] # define uma lista de palavras para serem ignoradas
nlp = spacy.blank("en") # cria um modelo em branco em inglês
ruler = nlp.add_pipe("entity_ruler") # adiciona o componente entity_ruler ao pipeline
letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" # define uma string com o alfabeto para os padrões
patterns = [] # inicializa a lista para armazenar os padrões de entidades
for symbol in symbols: # percorre a lista de símbolos de ações
    patterns.append({"label":"STOCK", "pattern": symbol}) # adiciona o símbolo com o rótulo stock
    for l in letters: # percorre cada letra do alfabeto
        patterns.append({"label":"STOCK", "pattern": symbol+f".{l}"}) # cria variações do símbolo seguidas de ponto e letra
for company in companies: # percorre a lista de nomes de empresas
    if company not in stops: # verifica se a empresa não deve ser ignorada
        patterns.append({"label":"COMPANY", "pattern": company}) # adiciona a empresa com o rótulo company
for index in indexes: # percorre a lista de índices financeiros
    patterns.append({"label":"INDEX", "pattern": index}) # adiciona o índice com o rótulo index
    words = index.split() # divide o nome do índice em palavras individuais
    patterns.append({"label":"INDEX", "pattern": "".join(words[:2])}) # cria um padrão com as duas primeiras palavras juntas
for index in index_symbols: # percorre os símbolos dos índices
    patterns.append({"label":"INDEX", "pattern": index}) # adiciona o símbolo do índice ao rótulo index
for e in exchanges: # percorre a lista de bolsas de valores
    patterns.append({"label": "STOCK_EXCHANGE", "pattern": e}) # adiciona a bolsa com o rótulo stock_exchange
ruler.add_patterns(patterns) # insere todos os padrões mapeados no entity_ruler

In [16]:
doc = nlp(text)
for ent in doc.ents: # itera sobre as entidades reconhecidas no doc
    print(ent.text, ent.label)

Apple 383
May this year 391
Cleveland Federal Reserve Bank 383
Loretta Mester's 380
around 19% 393
this year 391
dovish central bank 383
three 397
U.S. 384
Friday 391
U.S. 384
1:02 p.m. 392
ET 3286642859329048944
12.24 397
0.04% 393
34 397

In [17]:
text = '''
Report ad
Apple shares were set for their worst single-day fall since May this year, weighing on the NA

Sentiment also took a hit from Cleveland Federal Reserve Bank President Loretta Mester's comm

Investors have paid keen attention to the labor market and data hinting towards higher infla

The S&P 500 has risen around 19% so far this year on support from dovish central bank politie

Report ad
The three main U.S. indexes got some support on Friday from news of a phone call between U.S.

**At 1:02 p.m. ET, the Dow Jones Industrial Average (B2I) was up 12.24 points, or 0.04%, ● 34**
'''

In [14]:
from spacy import displacy

In [18]:
doc = nlp(text)
displacy.render(doc, style='ent')

In [20]:
df2 = pd.read_csv("indexes.tsv", delimiter="\t") # carrega o arquivo tsv para df2
indexes = df2.IndexName.tolist() # converte a coluna IndexName do dataframe
index_symbols = df2.IndexSymbol.tolist() # converte a coluna

In [21]:
df3 = pd.read_csv("stock_exchanges.tsv", sep = "\t")
df3

,BloombergExchangeCode,BloombergCompositeCode,Country,Description,ISOMIC,Google Prefix,EODcode,NumStocks
0,AF,AR,Argentina,Bolsa de Comercio de Buenos Aires,XBUE,NaN,BA,12
1,AO,AU,Australia,National Stock Exchange of Australia,XNEC,NaN,NaN,1
2,AT,AU,Australia,Asx - All Markets,XASX,ASX,AU,875
3,AV,NaN,Austria,Wiener Boerse Ag,XWBO,VIE,VI,38
4,BI,NaN,Bahrain,Bahrain Bourse,XBAH,NaN,NaN,4
...,...,...,...,...,...,...,...,...
97,UR,US,USA,NASDAQ Capital Market,XNCM,NASDAQ,US,"2,209"
98,UV,US,USA,OTC markets,OOTC,OTCMKTS,US,"2,433"
99,UW,US,USA,NASDAQ Global Select,XNGS,NASDAQ,US,"1,768"
100,VH,VN,Vietnam,Hanoi Stock Exchange,HSTC,NaN,NaN,4
101,VM,VN,Vietnam,Hochiminh Stock Exchange,XSTC,NaN,VN,40